### ISSUE TITLE
Minor typo at page 29 and 30

### ISSUE THREAD

**Issue by r4hulp** [robconery/feedback#35] opened 2016-08-21 05:46 UTC
Chapter Linux mentions about **"GNU/Linux"** but while rendering the PDF has got it as **"GNU\/Linux"** on page number 29 (second last line) and 30 (line number 3).

**Comment by rosswintle** [comment] 2016-08-21 20:08
Duplicate of #16 ?

**Comment by robconery** [comment] 2016-08-21 20:09
Yeah possibly - this is fixed and thanks!

**Closed as completed by robconery** 2016-08-21 20:09 UTC
