### ISSUE TITLE
Typo: Unbuntu

### ISSUE THREAD

**Issue by milmazz** [robconery/feedback#114] opened 2016-08-28 08:44 UTC
Format: PDF, Page: 89

> If you head over to nodejs.org you can find the script for installing NodeJS on
> Unbuntu:

`s/Unbuntu/Ubuntu/`

**Comment by alj1s** [comment] 2016-08-29 19:41
Duplicate of #24

**Comment by robconery** [comment] 2016-08-29 20:25
Crazy that I would let that slip through... but I think it's common :). This has been fixed and yes, it's a duplicate.

**Closed as completed by robconery** 2016-08-29 20:25 UTC
